// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Frequency string

const (
	FrequencyDaily   Frequency = "daily"
	FrequencyWeekly  Frequency = "weekly"
	FrequencyMonthly Frequency = "monthly"
	FrequencyYearly  Frequency = "yearly"
)

func (e *Frequency) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Frequency(s)
	case string:
		*e = Frequency(s)
	default:
		return fmt.Errorf("unsupported scan type for Frequency: %T", src)
	}
	return nil
}

type NullFrequency struct {
	Frequency Frequency `json:"frequency"`
	Valid     bool      `json:"valid"` // Valid is true if Frequency is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFrequency) Scan(value interface{}) error {
	if value == nil {
		ns.Frequency, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Frequency.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFrequency) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Frequency), nil
}

type TransactionType string

const (
	TransactionTypeIncome   TransactionType = "income"
	TransactionTypeExpense  TransactionType = "expense"
	TransactionTypeTransfer TransactionType = "transfer"
)

func (e *TransactionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionType(s)
	case string:
		*e = TransactionType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionType: %T", src)
	}
	return nil
}

type NullTransactionType struct {
	TransactionType TransactionType `json:"transaction_type"`
	Valid           bool            `json:"valid"` // Valid is true if TransactionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionType) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionType), nil
}

type UserTier string

const (
	UserTierFree       UserTier = "free"
	UserTierPro        UserTier = "pro"
	UserTierAtelierPro UserTier = "atelier_pro"
)

func (e *UserTier) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserTier(s)
	case string:
		*e = UserTier(s)
	default:
		return fmt.Errorf("unsupported scan type for UserTier: %T", src)
	}
	return nil
}

type NullUserTier struct {
	UserTier UserTier `json:"user_tier"`
	Valid    bool     `json:"valid"` // Valid is true if UserTier is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserTier) Scan(value interface{}) error {
	if value == nil {
		ns.UserTier, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserTier.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserTier) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserTier), nil
}

type Budget struct {
	ID          uuid.UUID      `json:"id"`
	UserID      pgtype.UUID    `json:"user_id"`
	CategoryID  pgtype.UUID    `json:"category_id"`
	LimitAmount pgtype.Numeric `json:"limit_amount"`
	Month       int32          `json:"month"`
	Year        int32          `json:"year"`
}

type Category struct {
	ID        uuid.UUID          `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	Icon      pgtype.Text        `json:"icon"`
	ColorHex  pgtype.Text        `json:"color_hex"`
	IsDefault pgtype.Bool        `json:"is_default"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RecurringBill struct {
	ID          uuid.UUID          `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	CategoryID  pgtype.UUID        `json:"category_id"`
	Name        string             `json:"name"`
	Amount      pgtype.Numeric     `json:"amount"`
	Frequency   NullFrequency      `json:"frequency"`
	NextDueDate pgtype.Date        `json:"next_due_date"`
	IsActive    pgtype.Bool        `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Transaction struct {
	ID              uuid.UUID          `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	Type            TransactionType    `json:"type"`
	Description     pgtype.Text        `json:"description"`
	MerchantName    pgtype.Text        `json:"merchant_name"`
	Date            pgtype.Date        `json:"date"`
	IsRecurring     pgtype.Bool        `json:"is_recurring"`
	RecurringBillID pgtype.UUID        `json:"recurring_bill_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	FullName     string             `json:"full_name"`
	PasswordHash string             `json:"password_hash"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	Tier         NullUserTier       `json:"tier"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
