// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateOrUpdateBudget(ctx context.Context, arg CreateOrUpdateBudgetParams) (Budget, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetBudgetByCategory(ctx context.Context, arg GetBudgetByCategoryParams) (Budget, error)
	GetMonthlySpendingOverview(ctx context.Context, arg GetMonthlySpendingOverviewParams) ([]GetMonthlySpendingOverviewRow, error)
	// Calculates the "Total Income" and "Total Expenses" for the current month
	GetMonthlySummary(ctx context.Context, userID pgtype.UUID) (GetMonthlySummaryRow, error)
	GetRecentTransactions(ctx context.Context, arg GetRecentTransactionsParams) ([]GetRecentTransactionsRow, error)
	GetSpendingOverview(ctx context.Context, arg GetSpendingOverviewParams) ([]GetSpendingOverviewRow, error)
	// Used to calculate total pages in the UI
	GetTransactionsCount(ctx context.Context, arg GetTransactionsCountParams) (int64, error)
	// Fetch transactions with pagination and date range filtering
	// Supports category-specific filtering if category_id is provided
	GetTransactionsFiltered(ctx context.Context, arg GetTransactionsFilteredParams) ([]GetTransactionsFilteredRow, error)
	GetUpcomingBills(ctx context.Context, userID pgtype.UUID) ([]RecurringBill, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserCategories(ctx context.Context, userID pgtype.UUID) ([]Category, error)
	GetUserCategoriesWithBudgets(ctx context.Context, arg GetUserCategoriesWithBudgetsParams) ([]GetUserCategoriesWithBudgetsRow, error)
	GetWeeklySpendingOverview(ctx context.Context, userID pgtype.UUID) ([]GetWeeklySpendingOverviewRow, error)
	ListBudgetsByMonth(ctx context.Context, arg ListBudgetsByMonthParams) ([]Budget, error)
	UpdateRecurringBillDate(ctx context.Context, arg UpdateRecurringBillDateParams) error
}

var _ Querier = (*Queries)(nil)
