// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
    user_id, name, icon, color_hex, is_default
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, name, icon, color_hex, is_default, created_at
`

type CreateCategoryParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Name      string      `json:"name"`
	Icon      pgtype.Text `json:"icon"`
	ColorHex  pgtype.Text `json:"color_hex"`
	IsDefault pgtype.Bool `json:"is_default"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.UserID,
		arg.Name,
		arg.Icon,
		arg.ColorHex,
		arg.IsDefault,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Icon,
		&i.ColorHex,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const createOrUpdateBudget = `-- name: CreateOrUpdateBudget :one
INSERT INTO budgets (
    user_id, 
    category_id, 
    limit_amount, 
    month, 
    year
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (user_id, category_id, month, year) 
DO UPDATE SET 
    limit_amount = EXCLUDED.limit_amount
RETURNING id, user_id, category_id, limit_amount, month, year
`

type CreateOrUpdateBudgetParams struct {
	UserID      pgtype.UUID    `json:"user_id"`
	CategoryID  pgtype.UUID    `json:"category_id"`
	LimitAmount pgtype.Numeric `json:"limit_amount"`
	Month       int32          `json:"month"`
	Year        int32          `json:"year"`
}

func (q *Queries) CreateOrUpdateBudget(ctx context.Context, arg CreateOrUpdateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, createOrUpdateBudget,
		arg.UserID,
		arg.CategoryID,
		arg.LimitAmount,
		arg.Month,
		arg.Year,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.LimitAmount,
		&i.Month,
		&i.Year,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    user_id, category_id, amount, type, description, merchant_name, date, is_recurring
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, user_id, category_id, amount, type, description, merchant_name, date, is_recurring, recurring_bill_id, created_at
`

type CreateTransactionParams struct {
	UserID       pgtype.UUID     `json:"user_id"`
	CategoryID   pgtype.UUID     `json:"category_id"`
	Amount       pgtype.Numeric  `json:"amount"`
	Type         TransactionType `json:"type"`
	Description  pgtype.Text     `json:"description"`
	MerchantName pgtype.Text     `json:"merchant_name"`
	Date         pgtype.Date     `json:"date"`
	IsRecurring  pgtype.Bool     `json:"is_recurring"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.CategoryID,
		arg.Amount,
		arg.Type,
		arg.Description,
		arg.MerchantName,
		arg.Date,
		arg.IsRecurring,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.Amount,
		&i.Type,
		&i.Description,
		&i.MerchantName,
		&i.Date,
		&i.IsRecurring,
		&i.RecurringBillID,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    full_name, email, password_hash, tier
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, email, full_name, password_hash, avatar_url, tier, created_at, updated_at
`

type CreateUserParams struct {
	FullName     string       `json:"full_name"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	Tier         NullUserTier `json:"tier"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FullName,
		arg.Email,
		arg.PasswordHash,
		arg.Tier,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Tier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBudgetByCategory = `-- name: GetBudgetByCategory :one
SELECT id, user_id, category_id, limit_amount, month, year FROM budgets
WHERE user_id = $1 
  AND category_id = $2 
  AND month = $3 
  AND year = $4
`

type GetBudgetByCategoryParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	CategoryID pgtype.UUID `json:"category_id"`
	Month      int32       `json:"month"`
	Year       int32       `json:"year"`
}

func (q *Queries) GetBudgetByCategory(ctx context.Context, arg GetBudgetByCategoryParams) (Budget, error) {
	row := q.db.QueryRow(ctx, getBudgetByCategory,
		arg.UserID,
		arg.CategoryID,
		arg.Month,
		arg.Year,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.LimitAmount,
		&i.Month,
		&i.Year,
	)
	return i, err
}

const getMonthlySummary = `-- name: GetMonthlySummary :one
SELECT 
    SUM(CASE WHEN type = 'income' THEN amount ELSE 0 END)::DECIMAL(15,2) as total_income,
    SUM(CASE WHEN type = 'expense' THEN amount ELSE 0 END)::DECIMAL(15,2) as total_expense
FROM transactions
WHERE user_id = $1 
  AND date >= date_trunc('month', CURRENT_DATE)
  AND date <= (date_trunc('month', CURRENT_DATE) + interval '1 month - 1 day')
`

type GetMonthlySummaryRow struct {
	TotalIncome  pgtype.Numeric `json:"total_income"`
	TotalExpense pgtype.Numeric `json:"total_expense"`
}

// Calculates the "Total Income" and "Total Expenses" for the current month
func (q *Queries) GetMonthlySummary(ctx context.Context, userID pgtype.UUID) (GetMonthlySummaryRow, error) {
	row := q.db.QueryRow(ctx, getMonthlySummary, userID)
	var i GetMonthlySummaryRow
	err := row.Scan(&i.TotalIncome, &i.TotalExpense)
	return i, err
}

const getRecentTransactions = `-- name: GetRecentTransactions :many
SELECT 
    t.id, t.user_id, t.category_id, t.amount, t.type, t.description, t.merchant_name, t.date, t.is_recurring, t.recurring_bill_id, t.created_at, 
    c.name as category_name, 
    c.icon as category_icon, 
    c.color_hex as category_color
FROM transactions t
LEFT JOIN categories c ON t.category_id = c.id
WHERE t.user_id = $1
ORDER BY t.date DESC, t.created_at DESC
LIMIT $2
`

type GetRecentTransactionsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

type GetRecentTransactionsRow struct {
	ID              uuid.UUID          `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	Type            TransactionType    `json:"type"`
	Description     pgtype.Text        `json:"description"`
	MerchantName    pgtype.Text        `json:"merchant_name"`
	Date            pgtype.Date        `json:"date"`
	IsRecurring     pgtype.Bool        `json:"is_recurring"`
	RecurringBillID pgtype.UUID        `json:"recurring_bill_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	CategoryName    pgtype.Text        `json:"category_name"`
	CategoryIcon    pgtype.Text        `json:"category_icon"`
	CategoryColor   pgtype.Text        `json:"category_color"`
}

func (q *Queries) GetRecentTransactions(ctx context.Context, arg GetRecentTransactionsParams) ([]GetRecentTransactionsRow, error) {
	rows, err := q.db.Query(ctx, getRecentTransactions, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentTransactionsRow
	for rows.Next() {
		var i GetRecentTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Amount,
			&i.Type,
			&i.Description,
			&i.MerchantName,
			&i.Date,
			&i.IsRecurring,
			&i.RecurringBillID,
			&i.CreatedAt,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionsCount = `-- name: GetTransactionsCount :one
SELECT COUNT(*) FROM transactions
WHERE user_id = $1
  AND (date >= $2 OR $2 IS NULL)
  AND (date <= $3 OR $3 IS NULL)
`

type GetTransactionsCountParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

// Used to calculate total pages in the UI
func (q *Queries) GetTransactionsCount(ctx context.Context, arg GetTransactionsCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getTransactionsCount, arg.UserID, arg.StartDate, arg.EndDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTransactionsFiltered = `-- name: GetTransactionsFiltered :many
SELECT 
    t.id,
    t.amount,
    t.type,
    t.description,
    t.merchant_name,
    t.date,
    t.is_recurring,
    c.name as category_name,
    c.icon as category_icon,
    c.color_hex as category_color
FROM transactions t
LEFT JOIN categories c ON t.category_id = c.id
WHERE t.user_id = $1
  AND (t.date >= $4 OR $4 IS NULL)
  AND (t.date <= $5 OR $5 IS NULL)
  AND (t.category_id = $6 OR $6 IS NULL)
ORDER BY t.date DESC, t.created_at DESC
LIMIT $2 OFFSET $3
`

type GetTransactionsFilteredParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
	StartDate  pgtype.Date `json:"start_date"`
	EndDate    pgtype.Date `json:"end_date"`
	CategoryID pgtype.UUID `json:"category_id"`
}

type GetTransactionsFilteredRow struct {
	ID            uuid.UUID       `json:"id"`
	Amount        pgtype.Numeric  `json:"amount"`
	Type          TransactionType `json:"type"`
	Description   pgtype.Text     `json:"description"`
	MerchantName  pgtype.Text     `json:"merchant_name"`
	Date          pgtype.Date     `json:"date"`
	IsRecurring   pgtype.Bool     `json:"is_recurring"`
	CategoryName  pgtype.Text     `json:"category_name"`
	CategoryIcon  pgtype.Text     `json:"category_icon"`
	CategoryColor pgtype.Text     `json:"category_color"`
}

// Fetch transactions with pagination and date range filtering
// Supports category-specific filtering if category_id is provided
func (q *Queries) GetTransactionsFiltered(ctx context.Context, arg GetTransactionsFilteredParams) ([]GetTransactionsFilteredRow, error) {
	rows, err := q.db.Query(ctx, getTransactionsFiltered,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
		arg.CategoryID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionsFilteredRow
	for rows.Next() {
		var i GetTransactionsFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Type,
			&i.Description,
			&i.MerchantName,
			&i.Date,
			&i.IsRecurring,
			&i.CategoryName,
			&i.CategoryIcon,
			&i.CategoryColor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpcomingBills = `-- name: GetUpcomingBills :many
SELECT id, user_id, category_id, name, amount, frequency, next_due_date, is_active, created_at FROM recurring_bills
WHERE user_id = $1 
  AND is_active = true 
  AND next_due_date <= (CURRENT_DATE + interval '30 days')
ORDER BY next_due_date ASC
`

func (q *Queries) GetUpcomingBills(ctx context.Context, userID pgtype.UUID) ([]RecurringBill, error) {
	rows, err := q.db.Query(ctx, getUpcomingBills, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurringBill
	for rows.Next() {
		var i RecurringBill
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Name,
			&i.Amount,
			&i.Frequency,
			&i.NextDueDate,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, full_name, password_hash, avatar_url, tier, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.PasswordHash,
		&i.AvatarUrl,
		&i.Tier,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserCategories = `-- name: GetUserCategories :many
SELECT id, user_id, name, icon, color_hex, is_default, created_at FROM categories
WHERE user_id = $1
ORDER BY name ASC
`

func (q *Queries) GetUserCategories(ctx context.Context, userID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, getUserCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Icon,
			&i.ColorHex,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserCategoriesWithBudgets = `-- name: GetUserCategoriesWithBudgets :many
SELECT 
    c.id,
    c.user_id,
    c.name,
    c.icon,
    c.color_hex,
    c.created_at,
    COALESCE(b.limit_amount, 0.00)::DECIMAL(15,2) as budget_limit,
    COALESCE(s.total_spent, 0.00)::DECIMAL(15,2) as total_spent,
    -- Calculate percentage for the progress bar, capped at 100 or allowed to exceed
    CASE 
        WHEN COALESCE(b.limit_amount, 0) = 0 THEN 0 
        ELSE ROUND((COALESCE(s.total_spent, 0) / b.limit_amount) * 100) 
    END as spent_percentage
FROM categories c
LEFT JOIN budgets b ON 
    c.id = b.category_id AND 
    b.month = $2 AND 
    b.year = $3
LEFT JOIN (
    /* Subquery to sum transactions for the given month/year */
    SELECT 
        category_id, 
        SUM(amount) as total_spent 
    FROM transactions 
    WHERE 
        EXTRACT(MONTH FROM date) = $2 AND 
        EXTRACT(YEAR FROM date) = $3 AND
        type = 'expense' -- Only count expenses toward the budget
    GROUP BY category_id
) s ON c.id = s.category_id
WHERE c.user_id = $1
ORDER BY c.name ASC
`

type GetUserCategoriesWithBudgetsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Month  int32       `json:"month"`
	Year   int32       `json:"year"`
}

type GetUserCategoriesWithBudgetsRow struct {
	ID              uuid.UUID          `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Name            string             `json:"name"`
	Icon            pgtype.Text        `json:"icon"`
	ColorHex        pgtype.Text        `json:"color_hex"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	BudgetLimit     pgtype.Numeric     `json:"budget_limit"`
	TotalSpent      pgtype.Numeric     `json:"total_spent"`
	SpentPercentage interface{}        `json:"spent_percentage"`
}

func (q *Queries) GetUserCategoriesWithBudgets(ctx context.Context, arg GetUserCategoriesWithBudgetsParams) ([]GetUserCategoriesWithBudgetsRow, error) {
	rows, err := q.db.Query(ctx, getUserCategoriesWithBudgets, arg.UserID, arg.Month, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserCategoriesWithBudgetsRow
	for rows.Next() {
		var i GetUserCategoriesWithBudgetsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Icon,
			&i.ColorHex,
			&i.CreatedAt,
			&i.BudgetLimit,
			&i.TotalSpent,
			&i.SpentPercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetsByMonth = `-- name: ListBudgetsByMonth :many
SELECT id, user_id, category_id, limit_amount, month, year FROM budgets
WHERE user_id = $1 
  AND month = $2 
  AND year = $3
`

type ListBudgetsByMonthParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Month  int32       `json:"month"`
	Year   int32       `json:"year"`
}

func (q *Queries) ListBudgetsByMonth(ctx context.Context, arg ListBudgetsByMonthParams) ([]Budget, error) {
	rows, err := q.db.Query(ctx, listBudgetsByMonth, arg.UserID, arg.Month, arg.Year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Budget
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.LimitAmount,
			&i.Month,
			&i.Year,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecurringBillDate = `-- name: UpdateRecurringBillDate :exec
UPDATE recurring_bills
SET next_due_date = $2, updated_at = now()
WHERE id = $1
`

type UpdateRecurringBillDateParams struct {
	ID          uuid.UUID   `json:"id"`
	NextDueDate pgtype.Date `json:"next_due_date"`
}

func (q *Queries) UpdateRecurringBillDate(ctx context.Context, arg UpdateRecurringBillDateParams) error {
	_, err := q.db.Exec(ctx, updateRecurringBillDate, arg.ID, arg.NextDueDate)
	return err
}
